spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/decp_user
    username: postgres
    password: kushan

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
