server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/decp_auth
    username: postgres
    password: kushan

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
